### ISSUE TITLE
Destroying assets is not permitted to avoid data loss.

### ISSUE THREAD

**Issue by xisigui** [MarcRubenEpacta/GameProgrammingProject#1]
Destroying assets is not permitted to avoid data loss.
If you really want to remove an asset use DestroyImmediate (theObject, true);
![image](https://user-images.githubusercontent.com/29411393/143003493-a291154e-1918-4145-b0a2-7ffc70ed3fa5.png)

Eto ata error

**Comment by MarcRubenEpacta** [comment]
oo mali yan pang physics lang pala yan

**Comment by xisigui** [comment]
Alisin ko?

**Comment by MarcRubenEpacta** [comment]
> Alisin ko?

sige
