### ISSUE TITLE
Background Music Suggestions

### ISSUE THREAD

**Issue by xisigui** [MarcRubenEpacta/GameProgrammingProject#5]
https://user-images.githubusercontent.com/29411393/143207230-741455b3-6add-456a-86e7-28240c4efecb.mp4

https://user-images.githubusercontent.com/29411393/143207577-521364ba-c461-4f0c-a5f4-7a6ad044769e.mp4

**Comment by MarcRubenEpacta** [comment]
yung track 4

**Comment by xisigui** [comment]
Lagay ko?
