### ISSUE TITLE
Bullet Impact Redesign Suggestion

### ISSUE THREAD

**Issue by xisigui** [MarcRubenEpacta/GameProgrammingProject#6]
**Effect 1**
![Effect 1](https://user-images.githubusercontent.com/29411393/143239858-9535d209-d9d7-4881-89e0-22914b376b56.gif)

**Effect 2**
![Effect 2](https://user-images.githubusercontent.com/29411393/143239902-251890a7-3bff-42b1-b80f-74ad05d0528b.gif)

**Effect 3**
![Effect 3](https://user-images.githubusercontent.com/29411393/143239942-ceef9ccb-bc37-47bc-89ce-270163c49fdb.gif)

**Effect 4**
![Effect 4](https://user-images.githubusercontent.com/29411393/143239962-3567f9b6-4198-4ae3-b085-13b8e8293209.gif)

**Comment by xisigui** [comment]
May add ako code sa bullet.cs naka comment lang luma code
![image](https://user-images.githubusercontent.com/29411393/143221648-7145df71-5695-4d68-87da-a1965b2d5ad3.png)

**Comment by MarcRubenEpacta** [comment]
okay sakin yung effect 4
